# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

language: cpp
dist: trusty

addons:
  apt:
    sources:
    # Clang 7:
      - llvm-toolchain-trusty-7
      - ubuntu-toolchain-r-test
    packages:
      - clang-7
      - cmake
      - doxygen
      - graphviz

script:
  - set -e
  - GTEST_VERSION=1.8.1
    ; GTEST_PREFIX=~/.local/
    ; wget https://github.com/google/googletest/archive/release-${GTEST_VERSION}.tar.gz
    && tar xf release-${GTEST_VERSION}.tar.gz
    && ( cd googletest-release-${GTEST_VERSION}/
      && cmake -DCVF_VERSION=${GTEST_VERSION} -DCMAKE_INSTALL_PREFIX:PATH=${GTEST_PREFIX} .
      && make
      && make install )
  - mkdir build
  - pushd build
  - compile_flags=(
        -pipe

        -O1
        -g
        -fsanitize=address
        -fno-omit-frame-pointer

        -Wall
        -Wextra
        -pedantic
    )
    && CFLAGS="${compile_flags[*]} -std=c89"
    && CXXFLAGS="${compile_flags[*]} -std=c++98"
    && cmake_args=(
        -DCMAKE_INSTALL_PREFIX:PATH=${GTEST_PREFIX}
    )
    && CC=clang-7
            CXX=clang++-7
            CFLAGS="${CFLAGS}"
            CXXFLAGS="${CXXFLAGS}"
            LDFLAGS='-g -fsanitize=address'
        cmake "${cmake_args[@]}" ..  # -Werror would fail checks!
  - make VERBOSE=1 C_FLAGS="${CFLAGS} -fPIC -Werror" CXX_FLAGS="${CXXFLAGS} -Werror" all
  - make VERBOSE=1 C_FLAGS="${CFLAGS} -fPIC -Werror" CXX_FLAGS="${CXXFLAGS} -Werror" test
  - cat Testing/Temporary/LastTest.log
  - make DESTDIR="${PWD}"/ROOT/ install
  - find ROOT | sort
  - popd
